 create table SENDEROS (
    id_sen int generated by default as identity,
    nombre varchar(50),
    direccion varchar (100),
    dificultad varchar (30),
    clima varchar (20),
    horario varchar(20),
    duracion varchar(5),
    primary key (id_sen)
  );
  
  ALTER TABLE SENDEROS ADD kilometros INT(3) NOT NULL AFTER dificultad;
  
  select * from senderos;
  
  select * from v$diag_info;